import numpy as np
a=np.arange(1,17).reshape(4,4)
print(a)
print("***************")
print(a[:])
print("***************")
print(a[1:])
print("***************")
print(a[:2])
print("***************")
print(a[:2,1:])
print("***************")
print(a[1,:2])
print("***************")
print(a[2,:3])
print("***************")
print(a[:,:2]) 